### ISSUE TITLE
チャンネル名のリネームに対応する

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog#13]
1. URL にチャンネル名を使わずチャンネル ID を使う
2. もしくはチャンネルがリネームされた場合、古いチャンネル名の URL から redirect する

**Comment by tyru** [comment]
話し合った結果チャンネル ID 一択な雰囲気

あと微妙にオフトピックだけど、今見てるチャンネルを確認するために↓の UI にしたい。

> 見てるチャンネルが分かりやすいように `position: sticky;` でチャンネル名含むタイトルを常時表示した方がいいかな？（パンくずで戻れるし）

**Comment by thinca** [comment]
export したログデータはチャンネル名のディレクトリに入っているのだけど、データを追加していくことを考えると JSON データのディレクトリ構成もチャンネル ID を使った方がよさそう。
変換スクリプトが必要。
