### ISSUE TITLE
vim-jp.slack.com 上のパーマリンクを取得したい

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog#37]
現在 https://vim-jp.org/slacklog/ 上でのパーマリンクは、ページ上で時刻をクリックすることでその URL に飛ぶことができる。
しかし vim-jp.slack.com 上のパーマリンクに飛びたい場合すぐ飛ぶことができない。
メッセージが消えている可能性もあるが、できれば vim-jp.slack.com 上のパーマリンクも取得したい。

**Comment by raa0121** [comment]
パーマリンク生成方法が分かったので、対応できそうです
