### ISSUE TITLE
Cannot publish the files that starts with "_"

### ISSUE THREAD

**Issue by thinca** [vim-jp/slacklog#44]
We have placing files under `files/` directory by any names, these contains start with "_".
But they are not published.

Ref: https://github.com/jekyll/jekyll/pull/8113

We should avoid by operation for example adds a prefix to each files.

**Comment by tyru** [comment]
vim-jp だし他の issue と同じく日本語でいいですよ

**Comment by thinca** [comment]
Jekyll の Issue にリンクしたので、困ってる人いるよアピールですw

**Comment by thinca** [comment]
We avoided by operation :)
https://github.com/vim-jp/slacklog/pull/46
