### ISSUE TITLE
メッセージに含まれる絵文字対応

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog#6]
投稿テキストの中に現れる `:tada:` のようなテキストを置換。

関連: #27

**Comment by tsuyoshicho** [comment]
via https://vim-jp.org/slacklog/lsp/2020/03/index.html#ts-1583894338.107700

> あ、それ採用:+1::skin-tone-5:

emojiのバリアントがあると変換できてないというか、slackおまかせな部分をフォローしないといけなさそうです。

(ちなみに、このskin-tone、なんか勝手に付くので、調整できてなくて毎度5になってる...

**Comment by tyru** [comment]
ちなみに skin tone は絵文字をクリックすると切り替わっていったはずですね

**Comment by tsuyoshicho** [comment]
ええ、ただリアクションのはできない(はず)ので、そっちでちょっと困ってるかな
普通のはできますね(ただ面倒...)

**Comment by thinca** [comment]
標準の絵文字の変換はこいつがやっている模様。
https://github.com/jekyll/jemoji
