### ISSUE TITLE
古い履歴に含まれる `./slacklog_data` を履歴改編で消す

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog#78]
> ログの底の方に slacklog_data が入っており、これが今のままだと削除できないので削除対応が必要になったときのために事前に消しておきたい

https://vim-jp.slack.com/archives/CRNLJDTU1/p1588437813087200

**Comment by thinca** [comment]
手元で rebase する予行演習ができました。あとはタイミングを見計らって #81 と一緒にやる。

**Comment by thinca** [comment]
新しくリポジトリを作り、こちらには古い履歴を消したブランチを push しました。
https://github.com/vim-jp/slacklog-generator
