### ISSUE TITLE
id 属性が valid ではない

### ISSUE THREAD

**Issue by mattn** [vim-jp/slacklog#8]
id 属性は英字から始まらないといけない。現状は `document.querySelector` できない。

**Comment by tyru** [comment]
ありがとうございます。修正しました e71354df1966faeeec7410ba547ab82a8d95966e

**Comment by tyru** [comment]
id で `.` とかが含まれる場合そのままではセレクタで使えないので、
`CSS.escape()` という関数を使ってエスケープしました。
（↓で初めて知った）

https://github.com/vim-jp/slacklog/blob/35c7d80d6c99d9c11fa0da758e8f12173a092225/assets/javascripts/slacklog.js#L7
